### ISSUE TITLE
Talking to OS

### ISSUE THREAD

**Issue by pathumego** [fontman/fontman-desktop-core#1]
fms should directly work with and talk to OS and platform font management. (ie: integrate with CS and CC font loading and caching systems) This helps to reliably provide remote service and also provide planned local cont management features as well. But for initial release the  function of `conflict handling` should be implemented.

**Comment by lpsandaruwan** [comment]
Using python library 'fontconfig', conflict handling can be done in Unix platforms. I'm not sure about Windows, in Windows, we can simply get a font list in Windows font directory, and compare with our fontman library. To manage the installed fonts in a system, if it is installed using a package manager we have to deal with the system's package manager.

**Comment by pathumego** [comment]
@Malintha any inputs in this area?

**Comment by malintha** [comment]
For linux, we can execute a command and get a list of installed fonts. Check this link : https://www.cyberciti.biz/tips/quickly-list-all-available-fonts.html

**Comment by pathumego** [comment]
@Malintha for unix fontconfig is the way to go. not sure about win

**Comment by lpsandaruwan** [comment]
Desktop application core now has API facilities to display all system fonts.

**Comment by lpsandaruwan** [comment]
This has been fixed and tested.
