### ISSUE TITLE
Windows Font installation

### ISSUE THREAD

**Issue by lpsandaruwan** [fontman/fontman-desktop-core#6]
Fix Installing a font in Windows.

**Comment by lpsandaruwan** [comment]
Seems like this one is a hard task. I'm moving with Mac and Linux until I found a solution.

**Comment by lpsandaruwan** [comment]
With the latest commit, Windows font installation has been fixed. But it is required to give FMS additional permissions to access Font library.

**Comment by davelab6** [comment]
Nice job dude!!

**Comment by lpsandaruwan** [comment]
Thanks Dave. :-)

**Comment by lpsandaruwan** [comment]
This has been tested and it is working perfectly.
